#!/bin/bash

# device="${BLOCK_INSTANCE:-wlp8s0}"
# status=$(cat /sys/class/net/${device}/operstate)
SIGNAL_QUALITY=$(nmcli d wifi | awk 'NR==2{print $7}')

echo $SIGNAL_QUALITY


if [ $SIGNAL_QUALITY -gt 75 ]; then 
  COLOR=$good_color
# > 50% quality
elif [ $SIGNAL_QUALITY -gt 50 ]; then
  COLOR=$ok_color
# > 25% quality
elif [ $SIGNAL_QUALITY -gt 25 ]; then
  COLOR=$notgood_color
elif [ $SIGNAL_QUALITY -gt 0 ]; then
# 0-25% link qual
  COLOR=$warn_color
else # < 25%
  COLOR=$rbad_color
fi

# printf "\e[0;%sm%s %s \e[m\n"  "$COLOR" "[$SIGNAL_QUALITY%]" "$link_name"
echo  "\e[0;%sm%s %s \e[m\n"  "$COLOR" "[$SIGNAL_QUALITY%]" 
